package net.avalon.authority.dao.bo;

import lombok.Data;
import lombok.NoArgsConstructor;
import net.avalon.authority.mapper.generator.po.UserPo;

import java.time.LocalDateTime;

/**
 * @Author: Weiyin
 * @Create: 2024/2/1 - 1:30
 */
@Data
@NoArgsConstructor
public class User {

    private Long id;

    private String userName;

    private String password;

    private String email;

    private Byte emailVerified;

    private String name;

    private String avatar;

    private LocalDateTime lastLoginTime;

    private String lastLoginIp;

    /**
     * Database Column Remarks:
     *   用户状态：
     *   1：正常
     *   <br>0：禁止
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.state
     *
     * @mbg.generated
     */
    private Byte state;

    private LocalDateTime createTime;

    private LocalDateTime updateTime;

    private String inviteCode;

    public UserPo toPo() {
        UserPo po = new UserPo();
        po.setUserName(this.userName);
        po.setPassword(this.password);
        po.setEmail(this.email);
        po.setName(this.name);
        po.setAvatar(this.avatar);
        return po;
    }

    public User(UserPo po){
        this.id = po.getId();
        this.userName = po.getUserName();
        this.password = po.getPassword();
        this.email = po.getEmail();
        this.emailVerified = po.getEmailVerified();
        this.name = po.getName();
        this.avatar = po.getAvatar();
        this.state = po.getState();
        this.lastLoginTime = po.getLastLoginTime();
        this.lastLoginIp = po.getLastLoginIp();
        this.createTime = po.getCreateTime();
        this.updateTime = po.getUpdateTime();
    }
}
