package net.avalon.authority.mapper.generator;

import java.util.List;
import net.avalon.authority.mapper.generator.po.InviteCodePo;
import net.avalon.authority.mapper.generator.po.InviteCodePoExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface InviteCodePoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invite_code
     *
     * @mbg.generated
     */
    long countByExample(InviteCodePoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invite_code
     *
     * @mbg.generated
     */
    int deleteByExample(InviteCodePoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invite_code
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invite_code
     *
     * @mbg.generated
     */
    int insert(InviteCodePo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invite_code
     *
     * @mbg.generated
     */
    int insertSelective(InviteCodePo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invite_code
     *
     * @mbg.generated
     */
    List<InviteCodePo> selectByExample(InviteCodePoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invite_code
     *
     * @mbg.generated
     */
    InviteCodePo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invite_code
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") InviteCodePo row, @Param("example") InviteCodePoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invite_code
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") InviteCodePo row, @Param("example") InviteCodePoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invite_code
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(InviteCodePo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invite_code
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(InviteCodePo row);
}