package net.avalon.authority.mapper.generator;

import java.util.List;
import net.avalon.authority.mapper.generator.po.PrivilegePo;
import net.avalon.authority.mapper.generator.po.PrivilegePoExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface PrivilegePoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table privilege
     *
     * @mbg.generated
     */
    long countByExample(PrivilegePoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table privilege
     *
     * @mbg.generated
     */
    int deleteByExample(PrivilegePoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table privilege
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table privilege
     *
     * @mbg.generated
     */
    int insert(PrivilegePo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table privilege
     *
     * @mbg.generated
     */
    int insertSelective(PrivilegePo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table privilege
     *
     * @mbg.generated
     */
    List<PrivilegePo> selectByExample(PrivilegePoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table privilege
     *
     * @mbg.generated
     */
    PrivilegePo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table privilege
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") PrivilegePo row, @Param("example") PrivilegePoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table privilege
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") PrivilegePo row, @Param("example") PrivilegePoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table privilege
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PrivilegePo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table privilege
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PrivilegePo row);
}