package net.avalon.authority.mapper.generator;

import java.util.List;
import net.avalon.authority.mapper.generator.po.RolePrivilegePo;
import net.avalon.authority.mapper.generator.po.RolePrivilegePoExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface RolePrivilegePoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_privilege
     *
     * @mbg.generated
     */
    long countByExample(RolePrivilegePoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_privilege
     *
     * @mbg.generated
     */
    int deleteByExample(RolePrivilegePoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_privilege
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_privilege
     *
     * @mbg.generated
     */
    int insert(RolePrivilegePo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_privilege
     *
     * @mbg.generated
     */
    int insertSelective(RolePrivilegePo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_privilege
     *
     * @mbg.generated
     */
    List<RolePrivilegePo> selectByExample(RolePrivilegePoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_privilege
     *
     * @mbg.generated
     */
    RolePrivilegePo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_privilege
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") RolePrivilegePo row, @Param("example") RolePrivilegePoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_privilege
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") RolePrivilegePo row, @Param("example") RolePrivilegePoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_privilege
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(RolePrivilegePo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_privilege
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(RolePrivilegePo row);
}