spring:
  datasource:
    #JDBC驱动
    driver-class-name: com.mysql.cj.jdbc.Driver
    #数据库服务器url
    url: jdbc:mysql://localhost:3306/ciallo?serverTimezone=Asia/Shanghai
    #数据库服务器用户名和密码
    username: root
    password: Hd15364514749+
    type: com.alibaba.druid.spring.boot3.autoconfigure.DruidDataSourceWrapper
    druid:
      initial-size: 10
      max-active: 16
      min-idle: 10
      validation-query: select 1

logging:
  level:
    root: info
  charset:
    console: utf-8