server:
  port: 0

spring:
  application:
    name: demo
  cloud:
    nacos:
      discovery:
#        server-addr: 156.224.21.142:8848
        server-addr: localhost
        username: user
        password: Ciallo～(∠・ω< )⌒☆