package net.avalon.mybatis.mapper.generator.po;

import lombok.Data;

import java.time.LocalDateTime;

/**
 * Database Table Remarks:
 *   漫画表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table comic
 */
@Data
public class ComicPo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comic.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   漫画译名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comic.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     * Database Column Remarks:
     *   漫画封面
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comic.cover
     *
     * @mbg.generated
     */
    private String cover;

    /**
     * Database Column Remarks:
     *   漫画作者
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comic.author
     *
     * @mbg.generated
     */
    private String author;

    /**
     * Database Column Remarks:
     *   漫画原名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comic.original_name
     *
     * @mbg.generated
     */
    private String originalName;

    /**
     * Database Column Remarks:
     *   汉化组
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comic.translator
     *
     * @mbg.generated
     */
    private String translator;

    /**
     * Database Column Remarks:
     *   简介
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comic.introduction
     *
     * @mbg.generated
     */
    private String introduction;

    /**
     * Database Column Remarks:
     *   观看次数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comic.view
     *
     * @mbg.generated
     */
    private Long view;

    /**
     * Database Column Remarks:
     *   0：连载中、1：已完结
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comic.status
     *
     * @mbg.generated
     */
    private Byte status;

    /**
     * Database Column Remarks:
     *   地区
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comic.region
     *
     * @mbg.generated
     */
    private String region;

    /**
     * Database Column Remarks:
     *   0：normal、1：R18
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comic.adult
     *
     * @mbg.generated
     */
    private Byte adult;

    /**
     * Database Column Remarks:
     *   分类 id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comic.category_id
     *
     * @mbg.generated
     */
    private Long categoryId;

    /**
     * Database Column Remarks:
     *   0：已删除<br />1：正常
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comic.deleted
     *
     * @mbg.generated
     */
    private Byte deleted;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comic.create_time
     *
     * @mbg.generated
     */
    private LocalDateTime createTime;

    /**
     * Database Column Remarks:
     *   更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comic.update_time
     *
     * @mbg.generated
     */
    private LocalDateTime updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comic.id
     *
     * @return the value of comic.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comic.id
     *
     * @param id the value for comic.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comic.name
     *
     * @return the value of comic.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comic.name
     *
     * @param name the value for comic.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comic.cover
     *
     * @return the value of comic.cover
     *
     * @mbg.generated
     */
    public String getCover() {
        return cover;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comic.cover
     *
     * @param cover the value for comic.cover
     *
     * @mbg.generated
     */
    public void setCover(String cover) {
        this.cover = cover == null ? null : cover.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comic.author
     *
     * @return the value of comic.author
     *
     * @mbg.generated
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comic.author
     *
     * @param author the value for comic.author
     *
     * @mbg.generated
     */
    public void setAuthor(String author) {
        this.author = author == null ? null : author.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comic.original_name
     *
     * @return the value of comic.original_name
     *
     * @mbg.generated
     */
    public String getOriginalName() {
        return originalName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comic.original_name
     *
     * @param originalName the value for comic.original_name
     *
     * @mbg.generated
     */
    public void setOriginalName(String originalName) {
        this.originalName = originalName == null ? null : originalName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comic.translator
     *
     * @return the value of comic.translator
     *
     * @mbg.generated
     */
    public String getTranslator() {
        return translator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comic.translator
     *
     * @param translator the value for comic.translator
     *
     * @mbg.generated
     */
    public void setTranslator(String translator) {
        this.translator = translator == null ? null : translator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comic.introduction
     *
     * @return the value of comic.introduction
     *
     * @mbg.generated
     */
    public String getIntroduction() {
        return introduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comic.introduction
     *
     * @param introduction the value for comic.introduction
     *
     * @mbg.generated
     */
    public void setIntroduction(String introduction) {
        this.introduction = introduction == null ? null : introduction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comic.view
     *
     * @return the value of comic.view
     *
     * @mbg.generated
     */
    public Long getView() {
        return view;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comic.view
     *
     * @param view the value for comic.view
     *
     * @mbg.generated
     */
    public void setView(Long view) {
        this.view = view;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comic.status
     *
     * @return the value of comic.status
     *
     * @mbg.generated
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comic.status
     *
     * @param status the value for comic.status
     *
     * @mbg.generated
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comic.region
     *
     * @return the value of comic.region
     *
     * @mbg.generated
     */
    public String getRegion() {
        return region;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comic.region
     *
     * @param region the value for comic.region
     *
     * @mbg.generated
     */
    public void setRegion(String region) {
        this.region = region == null ? null : region.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comic.adult
     *
     * @return the value of comic.adult
     *
     * @mbg.generated
     */
    public Byte getAdult() {
        return adult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comic.adult
     *
     * @param adult the value for comic.adult
     *
     * @mbg.generated
     */
    public void setAdult(Byte adult) {
        this.adult = adult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comic.category_id
     *
     * @return the value of comic.category_id
     *
     * @mbg.generated
     */
    public Long getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comic.category_id
     *
     * @param categoryId the value for comic.category_id
     *
     * @mbg.generated
     */
    public void setCategoryId(Long categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comic.deleted
     *
     * @return the value of comic.deleted
     *
     * @mbg.generated
     */
    public Byte getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comic.deleted
     *
     * @param deleted the value for comic.deleted
     *
     * @mbg.generated
     */
    public void setDeleted(Byte deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comic.create_time
     *
     * @return the value of comic.create_time
     *
     * @mbg.generated
     */
    public LocalDateTime getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comic.create_time
     *
     * @param createTime the value for comic.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comic.update_time
     *
     * @return the value of comic.update_time
     *
     * @mbg.generated
     */
    public LocalDateTime getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comic.update_time
     *
     * @param updateTime the value for comic.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(LocalDateTime updateTime) {
        this.updateTime = updateTime;
    }
}