server:
  port: 2333

spring:
  application:
    name: avalon-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 156.224.21.142:8848
        username: user
        password: Ciallo～(∠・ω< )⌒☆
    gateway:
      # 跨域
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins:
              - "*"
            allowed-headers:
              - "*"
            allowed-methods:
              - "*"
            exposed-headers:
              - "*"
            max-age: 3600
      routes:
        - id: demo-service
          uri: lb://demo # 这里的 "file-service" 是服务在 Nacos 中的名称
          predicates:
            - Path=/demo/**  # 例如所有以 /demo 开头的请求都会转发到文件服务
          filters:
            - StripPrefix=1  # 去掉请求路径中的前缀部分
            - Auth