server:
  port: 2333

spring:
  application:
    name: avalon-gateway
  data:
    redis:
      host: localhost
      port: 6379
      password: 123456
      database: 0
      timeout: 5000
      lettuce:
        pool:
          max-active: 100
          # 连接池中的最大空闲连接
          max-idle: 100
          # 连接池中的最小空闲连接
          min-idle: 0
          #连接池最大阻塞等待时间（使用负值表示没有限制）
          max-wait: -1
  cloud:
    nacos:
      discovery:
#        server-addr: 156.224.21.142:8848
        server-addr: localhost
        username: user
        password: Ciallo～(∠・ω< )⌒☆
    gateway:
      # 跨域
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins:
              - "*"
            allowed-headers:
              - "*"
            allowed-methods:
              - "*"
            exposed-headers:
              - "*"
            max-age: 3600
      routes:
        - id: demo-service
          uri: lb://demo # 这里的 "file-service" 是服务在 Nacos 中的名称
          predicates:
            - Path=/demo/**  # 例如所有以 /demo 开头的请求都会转发到文件服务
          filters:
            - StripPrefix=1  # 去掉请求路径中的前缀部分
            - Auth
        - id: user-service
          uri: lb://avalon-user
          predicates:
            - Path=/user-service/**
          filters:
            - StripPrefix=1
            - Auth
        - id: user-service-open
          uri: lb://avalon-user
          predicates:
            - Path=/open-user/**
          filters:
            - StripPrefix=1