server:
  port: 0

spring:
  application:
    name: nacos-demo
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
#        server-addr: 156.224.21.142:8848
        username: user
        password: Ciallo～(∠・ω< )⌒☆