package net.avalon.authority.mapper.generator.po;

import lombok.Data;

import java.time.LocalDateTime;

/**
 * Database Table Remarks:
 *   邀请码表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table invite_code
 */
@Data
public class InviteCodePo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invite_code.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   邀请码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invite_code.code
     *
     * @mbg.generated
     */
    private String code;

    /**
     * Database Column Remarks:
     *   可用次数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invite_code.available_count
     *
     * @mbg.generated
     */
    private Byte availableCount;

    /**
     * Database Column Remarks:
     *   创建者
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invite_code.create_by
     *
     * @mbg.generated
     */
    private Long createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invite_code.create_time
     *
     * @mbg.generated
     */
    private LocalDateTime createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invite_code.id
     *
     * @return the value of invite_code.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invite_code.id
     *
     * @param id the value for invite_code.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invite_code.code
     *
     * @return the value of invite_code.code
     *
     * @mbg.generated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invite_code.code
     *
     * @param code the value for invite_code.code
     *
     * @mbg.generated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invite_code.available_count
     *
     * @return the value of invite_code.available_count
     *
     * @mbg.generated
     */
    public Byte getAvailableCount() {
        return availableCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invite_code.available_count
     *
     * @param availableCount the value for invite_code.available_count
     *
     * @mbg.generated
     */
    public void setAvailableCount(Byte availableCount) {
        this.availableCount = availableCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invite_code.create_by
     *
     * @return the value of invite_code.create_by
     *
     * @mbg.generated
     */
    public Long getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invite_code.create_by
     *
     * @param createBy the value for invite_code.create_by
     *
     * @mbg.generated
     */
    public void setCreateBy(Long createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invite_code.create_time
     *
     * @return the value of invite_code.create_time
     *
     * @mbg.generated
     */
    public LocalDateTime getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invite_code.create_time
     *
     * @param createTime the value for invite_code.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }
}