package net.avalon.goodsdemo.mapper.generator;

import java.util.List;
import net.avalon.goodsdemo.mapper.generator.po.OnSalePo;
import net.avalon.goodsdemo.mapper.generator.po.OnSalePoExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface OnSalePoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_onsale
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_onsale
     *
     * @mbg.generated
     */
    int insert(OnSalePo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_onsale
     *
     * @mbg.generated
     */
    int insertSelective(OnSalePo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_onsale
     *
     * @mbg.generated
     */
    List<OnSalePo> selectByExample(OnSalePoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_onsale
     *
     * @mbg.generated
     */
    OnSalePo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_onsale
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") OnSalePo row, @Param("example") OnSalePoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_onsale
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") OnSalePo row, @Param("example") OnSalePoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_onsale
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(OnSalePo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_onsale
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(OnSalePo row);
}