package net.avalon.mybatis.mapper.generator;

import java.util.List;
import net.avalon.mybatis.mapper.generator.po.ComicPo;
import net.avalon.mybatis.mapper.generator.po.ComicPoExample;
import org.apache.ibatis.annotations.*;

@Mapper
public interface ComicPoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comic
     *
     * @mbg.generated
     */
    long countByExample(ComicPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comic
     *
     * @mbg.generated
     */
    int deleteByExample(ComicPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comic
     *
     * @mbg.generated
     */
    @Delete({
        "delete from comic",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comic
     *
     * @mbg.generated
     */
    @Insert({
        "insert into comic (name, cover, ",
        "author, original_name, ",
        "translator, introduction, ",
        "view, status, region, ",
        "adult, category_id, ",
        "deleted, create_time, ",
        "update_time)",
        "values (#{name,jdbcType=VARCHAR}, #{cover,jdbcType=VARCHAR}, ",
        "#{author,jdbcType=VARCHAR}, #{originalName,jdbcType=VARCHAR}, ",
        "#{translator,jdbcType=VARCHAR}, #{introduction,jdbcType=VARCHAR}, ",
        "#{view,jdbcType=BIGINT}, #{status,jdbcType=TINYINT}, #{region,jdbcType=VARCHAR}, ",
        "#{adult,jdbcType=TINYINT}, #{categoryId,jdbcType=BIGINT}, ",
        "#{deleted,jdbcType=TINYINT}, #{createTime,jdbcType=TIMESTAMP}, ",
        "#{updateTime,jdbcType=TIMESTAMP})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Long.class)
    int insert(ComicPo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comic
     *
     * @mbg.generated
     */
    int insertSelective(ComicPo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comic
     *
     * @mbg.generated
     */
    List<ComicPo> selectByExample(ComicPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comic
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, name, cover, author, original_name, translator, introduction, view, status, ",
        "region, adult, category_id, deleted, create_time, update_time",
        "from comic",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @ResultMap("net.avalon.mybatis.mapper.generator.ComicPoMapper.BaseResultMap")
    ComicPo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comic
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") ComicPo row, @Param("example") ComicPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comic
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") ComicPo row, @Param("example") ComicPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comic
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ComicPo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comic
     *
     * @mbg.generated
     */
    @Update({
        "update comic",
        "set name = #{name,jdbcType=VARCHAR},",
          "cover = #{cover,jdbcType=VARCHAR},",
          "author = #{author,jdbcType=VARCHAR},",
          "original_name = #{originalName,jdbcType=VARCHAR},",
          "translator = #{translator,jdbcType=VARCHAR},",
          "introduction = #{introduction,jdbcType=VARCHAR},",
          "view = #{view,jdbcType=BIGINT},",
          "status = #{status,jdbcType=TINYINT},",
          "region = #{region,jdbcType=VARCHAR},",
          "adult = #{adult,jdbcType=TINYINT},",
          "category_id = #{categoryId,jdbcType=BIGINT},",
          "deleted = #{deleted,jdbcType=TINYINT},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "update_time = #{updateTime,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(ComicPo row);
}